# Generated by Django 3.2.7 on 2021-10-13 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('genre', models.CharField(max_length=30, verbose_name='类别')),
                ('author', models.CharField(max_length=30, verbose_name='作者')),
                ('pub_date', models.DateField(blank=True, null=True, verbose_name='出版时间')),
                ('finish_date', models.DateField(blank=True, null=True, verbose_name='完成时间')),
                ('publisher', models.CharField(max_length=30, verbose_name='出版社')),
                ('overview', models.TextField(verbose_name='简介')),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='用户名')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
            ],
        ),
        migrations.CreateModel(
            name='BasicInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='实验室名称')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='邮箱')),
                ('mobile', models.CharField(blank=True, max_length=11, null=True, verbose_name='电话')),
                ('address', models.CharField(max_length=50, verbose_name='地址')),
                ('overview', models.TextField(verbose_name='简介')),
                ('history', models.TextField(verbose_name='发展历史')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=50, verbose_name='文件名')),
                ('image', models.ImageField(upload_to='media/images')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('overview', models.CharField(max_length=100, verbose_name='简述')),
                ('content', models.TextField(blank=True, null=True, verbose_name='内容')),
                ('img', models.ImageField(upload_to='media')),
                ('date', models.DateTimeField()),
                ('text_file', models.FileField(upload_to='upload/news')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('genre', models.CharField(max_length=30, verbose_name='类别')),
                ('source', models.CharField(max_length=50, verbose_name='来源')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='开始时间')),
                ('finish_date', models.DateField(blank=True, null=True, verbose_name='完成时间')),
                ('budget', models.FloatField(verbose_name='项目经费')),
                ('role', models.CharField(max_length=30, verbose_name='担任角色')),
                ('status', models.CharField(max_length=50, verbose_name='项目状态')),
            ],
        ),
        migrations.CreateModel(
            name='ResearchField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('overview', models.CharField(max_length=100, verbose_name='简述')),
                ('content', models.TextField(blank=True, null=True, verbose_name='内容')),
                ('img', models.ImageField(upload_to='media')),
                ('date', models.DateTimeField()),
                ('text_file', models.FileField(upload_to='upload/research')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='姓名')),
                ('homepage', models.CharField(blank=True, max_length=50, null=True, verbose_name='主页地址')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='邮箱')),
                ('photo', models.ImageField(upload_to='media/photo')),
                ('degree', models.CharField(max_length=30, verbose_name='学位')),
                ('overview', models.TextField(verbose_name='简介')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='姓名')),
                ('homepage', models.CharField(blank=True, max_length=50, null=True, verbose_name='主页地址')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='邮箱')),
                ('photo', models.ImageField(upload_to='media/photo')),
                ('professional_title', models.CharField(max_length=30, verbose_name='职称')),
                ('introduction', models.TextField(blank=True, null=True, verbose_name='基本信息')),
                ('mobile', models.CharField(blank=True, max_length=11, null=True, verbose_name='电话')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
