# Generated by Django 3.2.8 on 2021-10-26 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('description', models.CharField(max_length=50, verbose_name='描述')),
                ('image_name', models.CharField(max_length=50, verbose_name='图片名')),
                ('image', models.ImageField(upload_to='images/fields')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(default='', upload_to='images/project'),
        ),
        migrations.AddField(
            model_name='project',
            name='image_name',
            field=models.CharField(default='', max_length=50, verbose_name='图片名'),
        ),
        migrations.AlterField(
            model_name='project',
            name='budget',
            field=models.CharField(max_length=50, verbose_name='项目经费'),
        ),
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(upload_to='images/people'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.ImageField(upload_to='images/people'),
        ),
    ]
