# Generated by Django 3.2.8 on 2021-10-17 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20211015_0913'),
    ]

    operations = [
        migrations.CreateModel(
            name='Papers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('overview', models.CharField(max_length=100, verbose_name='简述')),
                ('filename', models.CharField(blank=True, max_length=50, null=True, verbose_name='文件名')),
                ('img', models.ImageField(upload_to='media')),
                ('date', models.CharField(max_length=50, verbose_name='日期')),
                ('text_file', models.FileField(upload_to='upload/papers')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='ResearchField',
        ),
        migrations.RemoveField(
            model_name='news',
            name='content',
        ),
        migrations.AddField(
            model_name='image',
            name='image_name',
            field=models.CharField(default='1', max_length=50, verbose_name='图片名'),
        ),
        migrations.AddField(
            model_name='news',
            name='filename',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='文件名'),
        ),
        migrations.AlterField(
            model_name='achievements',
            name='finish_date',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='完成时间'),
        ),
        migrations.AlterField(
            model_name='achievements',
            name='pub_date',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='出版时间'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='media/images'),
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.CharField(max_length=50, verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='project',
            name='finish_date',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='完成时间'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(upload_to='media/images'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(upload_to='media/images'),
        ),
    ]
