# Generated by Django 3.2.8 on 2021-10-26 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20211026_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='images/project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image_name',
            field=models.CharField(max_length=50, verbose_name='图片名'),
        ),
    ]
