# Generated by Django 3.2.8 on 2021-10-28 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_auto_20211026_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.CharField(default='', max_length=50, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image_name',
            field=models.CharField(default='', max_length=50, verbose_name='图片名'),
        ),
        migrations.AlterField(
            model_name='papers',
            name='image_name',
            field=models.CharField(default='', max_length=50, verbose_name='图片名'),
        ),
    ]
