# Generated by Django 3.2.8 on 2021-10-29 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_auto_20211028_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievements',
            name='finish_date',
        ),
        migrations.RemoveField(
            model_name='papers',
            name='date',
        ),
        migrations.RemoveField(
            model_name='papers',
            name='filename',
        ),
        migrations.RemoveField(
            model_name='papers',
            name='image',
        ),
        migrations.RemoveField(
            model_name='papers',
            name='image_name',
        ),
        migrations.RemoveField(
            model_name='papers',
            name='overview',
        ),
        migrations.RemoveField(
            model_name='papers',
            name='show',
        ),
        migrations.RemoveField(
            model_name='papers',
            name='text_file',
        ),
        migrations.RemoveField(
            model_name='papers',
            name='title',
        ),
        migrations.AddField(
            model_name='papers',
            name='link',
            field=models.CharField(default='', max_length=50, verbose_name='链接'),
        ),
        migrations.AddField(
            model_name='papers',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='images/projects'),
        ),
    ]
