# Generated by Django 3.2.8 on 2021-10-20 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_alter_image_image_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='show',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
