# Generated by Django 3.2.8 on 2021-10-20 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_news_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='img_name',
            field=models.CharField(default='/static/images/default/header.png', max_length=50, verbose_name='图片名'),
        ),
        migrations.AddField(
            model_name='papers',
            name='img_name',
            field=models.CharField(default='/static/images/default/header.png', max_length=50, verbose_name='图片名'),
        ),
        migrations.AddField(
            model_name='papers',
            name='show',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.CharField(default='XXXX-XX-XX', max_length=50, verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='news',
            name='img',
            field=models.ImageField(upload_to='media/images'),
        ),
        migrations.AlterField(
            model_name='news',
            name='overview',
            field=models.CharField(default='点击开始新建条目', max_length=100, verbose_name='简述'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(default='新建条目', max_length=50, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='papers',
            name='date',
            field=models.CharField(default='XXXX-XX-XX', max_length=50, verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='papers',
            name='img',
            field=models.ImageField(upload_to='media/images'),
        ),
        migrations.AlterField(
            model_name='papers',
            name='overview',
            field=models.CharField(default='点击开始新建条目', max_length=100, verbose_name='简述'),
        ),
        migrations.AlterField(
            model_name='papers',
            name='title',
            field=models.CharField(default='新建条目', max_length=50, verbose_name='标题'),
        ),
    ]
