# Generated by Django 3.2.8 on 2021-10-29 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_auto_20211029_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='papers',
            name='link',
            field=models.CharField(max_length=50, verbose_name='链接'),
        ),
        migrations.AlterField(
            model_name='papers',
            name='name',
            field=models.CharField(max_length=100, verbose_name='内容'),
        ),
    ]
